-- create a masking policy
CREATE OR REPLACE MASKING POLICY CUSTOMER_MASK AS (val string) returns string ->
CASE
WHEN CURRENT_ROLE() IN ('DEVELOPER') THEN VAL
ELSE '*********'
END;

-- add the masking policy to tables
ALTER TABLE IF EXISTS PATRICKDB.DWH_DBO.CUSTOMER MODIFY COLUMN EMAIL SET MASKING POLICY CUSTOMER_MASK;
ALTER TABLE IF EXISTS PATRICKDB.DWH_DBO.CUSTOMER MODIFY COLUMN STREET SET MASKING POLICY CUSTOMER_MASK;
ALTER TABLE IF EXISTS PATRICKDB.DWH_DBO.CUSTOMER MODIFY COLUMN CITY SET MASKING POLICY CUSTOMER_MASK;
ALTER TABLE IF EXISTS PATRICKDB.DWH_DBO.CUSTOMER MODIFY COLUMN ZIP_CODE SET MASKING POLICY CUSTOMER_MASK;
ALTER TABLE IF EXISTS PATRICKDB.DWH_DBO.BANKING_DETAILS MODIFY COLUMN CC_NUMBER SET MASKING POLICY CUSTOMER_MASK;
